# Generated by Django 5.0.6 on 2024-10-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworksModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network_name', models.CharField(max_length=50)),
                ('net_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('token', models.TextField()),
                ('secret', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'networks',
            },
        ),
    ]
