# Generated by Django 5.0.6 on 2024-08-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
