# Generated by Django 5.0.6 on 2024-10-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_alter_networksmodel_user'),
        ('posts', '0002_alter_postsmodel_image_alter_postsmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsNetworksModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.networksmodel')),
            ],
            options={
                'db_table': 'posts_networks',
            },
        ),
    ]
