# Generated by Django 5.0.6 on 2024-11-08 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postsnetworksmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
