# Generated by Django 5.0.6 on 2024-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postsmodel_scheduled_alter_postsmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
